
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsniwtylfznqrovrvlwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzbml3dHlsZnpucXJvdnJ2bHd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MDYwNTgsImV4cCI6MjA2MTE4MjA1OH0.IL3Jez5e3uPlg6WtuLX0MKd3387TiZI_L_eQbVHNkew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
        'apikey': SUPABASE_PUBLISHABLE_KEY,
      },
    },
  }
);
